---
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirect HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Let's Encrypt
      - "--certificatesresolvers.le.acme.email=maikel@vandenbosch.dev"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

      # Tell Traefik which network to use
      - "--providers.docker.network=proxy"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /letsencrypt:/letsencrypt

    labels:
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=le"

      - "traefik.http.routers.traefik.rule=Host(`code-traefik.vandenbosch.dev`)" # ← dit mist!
      - "traefik.http.routers.traefik.tls=true"

      # Tell router to use internal api service
      - "traefik.http.routers.traefik.service=api@internal"

      # # Optional: basic auth middleware
      # - "traefik.http.routers.traefik.middlewares=traefik-auth"

    networks:
      - proxy

networks:
  proxy:
    external: true
